cc_library(
    name = "firelib",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(["**/*.hpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "@bazelrio//libraries/cpp/wpilib/wpilibc",
    ],
)