load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
local_repository(
    name = "bazelrio",
    path = "../bazelrio",
)

load("@bazelrio//:deps.bzl", "setup_bazelrio_dependencies")

setup_bazelrio_dependencies()

load("@bazelrio//:defs.bzl", "setup_bazelrio")

setup_bazelrio()